name: SPA C.I.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-all: 
                          
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup SPA Node
      uses: actions/setup-node@v3
      with:
        node-version: 16.18.x
        cache: 'npm '
      
    - name: Build & Test SPA Node
      run: echo 'Building and Testing Node'
        && npm install nodemon --save
        && npm run-script -build
